spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/ming_commerce
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate


jwt:
  access-token-duration: 604800000 # valid 1 Week
  refresh-token-duration: 2419200000 # valid 1 Month
  secret-key: igPdT8viN5t8iToOn5sfqbqASzDFlsJze16OggGsDJauk2egG5

admin:
  email: admin@ming.com
  password: 1234