spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/ming_commerce
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    username: ${MING_MAIL_SENDER_EMAIL} # TODO 테스트를 위해서는 개인 이메일 계정을 환경변수에 세팅해주세요. 추후 밍커머스 이메일 계정으로 바꾸어야 합니다.
    password: ${MING_MAIL_SENDER_PASSWORD}

jwt:
  access-token-duration: 604800000 # valid 1 Week
  refresh-token-duration: 2419200000 # valid 1 Month
  secret-key: igPdT8viN5t8iToOn5sfqbqASzDFlsJze16OggGsDJauk2egG5

admin:
  email: admin@ming.com
  password: 1234

toss:
  payments:
    secret-key: ${TOSS_SECRET_KEY}

ming:
  domain: ${MING_DOMAIN}
