ifndef::snippets[]
:snippets: build/generated-snippets
endif::[]
:doctitle: Ming Commerce API Document
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

MingCommerce 백엔드 API 문서입니다.

=== JIRA :

https://ming-commerce.atlassian.net/jira/software/projects/MING/boards/4/roadmap[MingCommerce]

=== GIT :

https://github.com/ming-veloper/ming-commerce[Github]

== Member

=== 회원 등록

operation::register-member[]

=== 이메일 중복 여부 체크

operation::check-email-duplication[]

=== 로그인

operation::login[]

=== 멤버 정보 반환

operation::get-member-info[]

== Product

=== 상품 데이터 삽입

amazom.com 의 grocery 카테고리의 상품을 크롤링하여 DB 에 삽입한다.

operation::insert-product[]

=== 상품 조회하기

카테고리이름과 페이지를 queryParam 으로 해서 해당 카테고리에 속한 상품을 10개씩 조회한다. 0 페이지부터 시작한다.

operation::get-products[]

=== 상품 상세 조회하기

상세설명, 상품 이미지들을 포함한 상품의 상세를 조회한다.

operation::get-product-detail[]

== Cart

=== 장바구니 상품 조회하기

장바구니의 상품을 조회한다. 삭제여부가 false 인 상품만을 조회한다.

operation::get-cart-products[]

=== 장바구니에 상품 담기

상품 아이디(productId) 와 수량(quantity)를 쿼리파라미터로 하여 장바구니에 상품을 담는다.
quantity 파라미터가 없다면 자동 1로 세팅된다.

이전에 해당 상품을 저장한 적이 있다면 기존 quantity 에 파라미터로 들어온 quantity 가 더해진다.

operation::add-product-to-cart[]

=== 장바구니에 담긴 상품 수량 수정하기

장바구니에 담긴 상품의 수량을 수정한다.

operation::update-cart-product-quantity[]

=== 장바구니에 담긴 상품 삭제하기

장바구니에 담긴 상품을 삭제한다.

operation::delete-cart-product[]

== Order

=== 장바구니에 담긴 상품 주문하기

장바구니에 담긴 상품을 주문한다.
CartLine 의 고유 id인 uuid 로 장바구니 안의 상품을 선택하여 주문할 수 있다.

operation::order[]

=== 주문 아이디로 해당 주문 조회하기

주문 ID 를 쿼리 파라미터로 하여 주문을 조회한다.
해당 주문 조회에 권한이 있는 사용자만 조회가 가능하다.

operation::get-order-by-id[]

=== 주문 상세 조회하기

주문 ID 를 쿼리 파리미터로 하여 주문 상세를 조회한다.

operation::get-order-detail[]

=== 사용자의 주문 조회하기

사용자의 주문을 최대 5개까지 조회한다.
각 주문의 주문 아이디, 주문 이름, 총 결제 금액, 주문 상태를 반환한다.

operation::get-my-order[]

== Payment

=== 결제 승인 (토스 결제)

결제 요청 검증 후 결제를 승인한다.

operation::payment-approval[]
