name: ming-commerce-backend-master-deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      # Install Python 3.9
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Install the EB CLI using pip
      - name: Install EB CLI
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli

      - name: Display EB CLI Version
        run: |
          eb --version
        shell: bash

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: |
          ./gradlew clean build
        shell: bash

      - name: Release with EB CLI
        run: |
          eb setenv SPRING_PROFILES_ACTIVE=prod
          eb deploy